### ISSUE TITLE
Backport fixes and features for FVTT 0.7.x and SW 1.4

### ISSUE THREAD

**Issue by wrycu** [wrycu/StarWarsFFG-Enhancements#79]
- [x] Show minion group max size
- [x] Ability to use actor dice from vehicle weapon rolls (#76)
- [x] Correct shop dice pool generation
- [x] Improve attack animations for players (#77)
- [x] Actor renaming resetting on reload
- [x] Inability to roll on certain items (#72, #65)
- [x] Add attack animation settings for grenades (#46)
- [x] Remember shop settings (#56)
- [x] Allow players to use dice result spender (#51)
- [x] Fix for dice result spender generating new buttons when scrolling through chat history
- [x] Attack animation filepicker doesn't work

**Comment by wrycu** [comment]
Note that these features will be on a different branch and likely won't be able to be applied automatically (via an update) due to the limited nature of how Foundry modules work.

**Comment by wrycu** [comment]
Okay, in theory there is now feature parity between this and the latest 0.8.x release.  I'll do some testing and then attempt a release.
